# Generated by Django 5.1.7 on 2025-03-21 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('accounts', '0001_initial'), ('accounts', '0002_student_extra_data_student_gender_student_teacher_and_more'), ('accounts', '0003_remove_teacher_preferred_location'), ('accounts', '0004_remove_teacher_title_teacher_english_level'), ('accounts', '0005_rename_degree_teacher_teaching_certificate_and_more')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specialties', models.CharField(blank=True, max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
                ('available_time', models.TextField(blank=True)),
                ('teaching_certificate', models.CharField(blank=True, max_length=100)),
                ('emergency_contact', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('id_number', models.CharField(blank=True, max_length=18)),
                ('major', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('teaching_years', models.PositiveIntegerField(default=0)),
                ('university', models.CharField(blank=True, max_length=200)),
                ('english_level', models.CharField(blank=True, choices=[('cet4', 'CET-4'), ('cet6', 'CET-6'), ('ielts', 'IELTS'), ('toefl', 'TOEFL'), ('professional', '专业英语'), ('native', '母语'), ('other', '其他')], max_length=50)),
                ('education_level', models.CharField(blank=True, choices=[('bachelor', '学士'), ('master', '硕士'), ('phd', '博士'), ('other', '其他')], max_length=50)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('work_status', models.CharField(blank=True, choices=[('full_time', '全职'), ('part_time', '兼职'), ('freelance', '自由职业')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(blank=True, choices=[('beginner', '初级'), ('intermediate', '中级'), ('advanced', '高级'), ('proficient', '精通')], max_length=50)),
                ('interests', models.CharField(blank=True, max_length=200)),
                ('learning_goal', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
                ('gender', models.CharField(blank=True, choices=[('male', '男'), ('female', '女'), ('other', '其他')], max_length=10)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='accounts.teacher')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
