# Generated by Django 5.1.7 on 2025-04-08 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial_squashed_0005_rename_degree_teacher_teaching_certificate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.CharField(blank=True, choices=[('primary_1', '小学一年级'), ('primary_2', '小学二年级'), ('primary_3', '小学三年级'), ('primary_4', '小学四年级'), ('primary_5', '小学五年级'), ('primary_6', '小学六年级'), ('junior_1', '初中一年级'), ('junior_2', '初中二年级'), ('junior_3', '初中三年级'), ('senior_1', '高中一年级'), ('senior_2', '高中二年级'), ('senior_3', '高中三年级'), ('college_1', '大学一年级'), ('college_2', '大学二年级'), ('college_3', '大学三年级'), ('college_4', '大学四年级'), ('graduate', '研究生'), ('other', '其他')], max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='province',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='province',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='StudentTeacherRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_relationships', to='accounts.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_relationships', to='accounts.teacher')),
            ],
            options={
                'unique_together': {('student', 'teacher')},
            },
        ),
    ]
