# Generated by Django 5.1.7 on 2025-04-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_student_teacher_student_age_student_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='learning_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='累计学习时长(小时)'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='电话号码'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teaching_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='累计教学时长(小时)'),
        ),
    ]
