# Generated by Django 5.1.7 on 2025-04-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_student_learning_hours_student_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='interests',
        ),
        migrations.AddField(
            model_name='student',
            name='personality_traits',
            field=models.CharField(blank=True, max_length=200, verbose_name='性格特点'),
        ),
    ]
