# Generated by Django 5.1.7 on 2025-04-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_student_interests_student_personality_traits'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='real_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='真实姓名'),
        ),
    ]
