# Generated by Django 5.1.7 on 2025-04-22 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_student_real_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='learning_hours',
        ),
    ]
