# Generated by Django 5.1.7 on 2025-04-23 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_teacher_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='teaching_hours',
        ),
    ]
