# Generated by Django 5.1.7 on 2025-05-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_teacher_teaching_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='real_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='真实姓名'),
        ),
    ]
