# Generated by Django 5.1.7 on 2025-05-20 15:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_teacher_real_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WechatLoginSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polling_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('status', models.CharField(choices=[('PENDING', '等待中'), ('SUCCESS', '成功'), ('TIMEOUT', '超时')], default='PENDING', max_length=16)),
                ('token', models.TextField(blank=True, null=True)),
                ('user_info', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '微信登录会话',
                'verbose_name_plural': '微信登录会话',
            },
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='emergency_contact',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='emergency_contact_phone',
        ),
    ]
