# Generated by Django 5.2.1 on 2025-05-21 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_wechatloginsession_remove_teacher_emergency_contact_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WechatLoginSession',
        ),
    ]
