# Generated by Django 5.1.7 on 2025-04-13 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_remove_student_interests_student_personality_traits'),
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words_per_day', models.IntegerField(verbose_name='每日新单词量')),
                ('start_date', models.DateField(verbose_name='计划开始日期')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否为当前正在学习的计划')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_plans', to='accounts.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_learning_plans', to='accounts.teacher', verbose_name='负责老师')),
                ('vocabulary_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_plans', to='vocabulary.vocabularybook')),
            ],
            options={
                'verbose_name': '学习计划',
                'verbose_name_plural': '学习计划',
                'db_table': 'learning_plans',
            },
        ),
        migrations.CreateModel(
            name='LearningUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.IntegerField(verbose_name='单元序号')),
                ('start_word_order', models.IntegerField(verbose_name='单元起始单词序号')),
                ('end_word_order', models.IntegerField(verbose_name='单元结束单词序号')),
                ('expected_learn_date', models.DateField(verbose_name='计划学习日期')),
                ('is_learned', models.BooleanField(default=False, verbose_name='是否已学习')),
                ('learned_at', models.DateTimeField(blank=True, null=True, verbose_name='完成学习时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learning_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='learning.learningplan')),
            ],
            options={
                'verbose_name': '学习单元',
                'verbose_name_plural': '学习单元',
                'db_table': 'learning_units',
            },
        ),
        migrations.CreateModel(
            name='UnitReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField(verbose_name='艾宾浩斯计划复习日期')),
                ('review_order', models.IntegerField(verbose_name='第几次复习(1-5)')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否已完成')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learning_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='learning.learningunit')),
            ],
            options={
                'verbose_name': '单元复习记录',
                'verbose_name_plural': '单元复习记录',
                'db_table': 'unit_reviews',
            },
        ),
        migrations.AddIndex(
            model_name='learningplan',
            index=models.Index(fields=['student', 'vocabulary_book'], name='idx_student_book'),
        ),
        migrations.AddIndex(
            model_name='learningplan',
            index=models.Index(fields=['student', 'is_active'], name='idx_student_active'),
        ),
        migrations.AddIndex(
            model_name='learningplan',
            index=models.Index(fields=['teacher'], name='idx_teacher'),
        ),
        migrations.AddIndex(
            model_name='learningunit',
            index=models.Index(fields=['learning_plan', 'unit_number'], name='idx_plan_unit'),
        ),
        migrations.AddIndex(
            model_name='learningunit',
            index=models.Index(fields=['expected_learn_date'], name='idx_learn_date'),
        ),
        migrations.AddIndex(
            model_name='unitreview',
            index=models.Index(fields=['review_date'], name='idx_review_date'),
        ),
        migrations.AlterUniqueTogether(
            name='unitreview',
            unique_together={('learning_unit', 'review_order')},
        ),
    ]
