# Generated by Django 5.1.7 on 2025-05-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningunit',
            name='end_word_order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='learningunit',
            name='expected_learn_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='learningunit',
            name='is_learned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='learningunit',
            name='learned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='learningunit',
            name='start_word_order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='learningunit',
            name='unit_number',
            field=models.IntegerField(),
        ),
    ]
