# Generated by Django 5.1.7 on 2025-06-06 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_alter_learningunit_end_word_order_and_more'),
        ('vocabulary', '0003_studentknownword'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordLearningStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage', models.IntegerField(default=0, verbose_name='当前学习阶段(0-5)')),
                ('start_date', models.DateField(verbose_name='首次学习日期')),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='最后复习时间')),
                ('next_review_date', models.DateField(blank=True, null=True, verbose_name='下次复习日期')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_stages', to='vocabulary.bookword')),
                ('learning_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_stages', to='learning.learningplan')),
            ],
            options={
                'verbose_name': '单词学习阶段',
                'verbose_name_plural': '单词学习阶段',
                'db_table': 'word_learning_stages',
                'indexes': [models.Index(fields=['learning_plan', 'current_stage'], name='idx_plan_stage'), models.Index(fields=['next_review_date'], name='idx_next_review'), models.Index(fields=['learning_plan', 'next_review_date'], name='idx_plan_review_date')],
                'unique_together': {('learning_plan', 'book_word')},
            },
        ),
    ]
