# Generated by Django 5.2.1 on 2025-06-08 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_wordlearningstage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnitReview',
        ),
        migrations.DeleteModel(
            name='LearningUnit',
        ),
    ]
