"""
Django settings for englishlearning project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import sys
import datetime
from django.utils import timezone

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 添加apps目录到Python路径
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))

# ====== 全局时间Mock，仅测试用 ======
# if os.environ.get("MOCK_DAYS"):
#     days = int(os.environ.get("MOCK_DAYS", "0"))
#     def mock_now():
#         real_now = datetime.datetime.now(timezone.get_current_timezone())
#         return real_now + datetime.timedelta(days=days)
#     timezone.now = mock_now
# ====== END ======

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!sfl=ojjf7_&uh-p0s*_fi)m!^b-7=^^)xt5i1nlt-@re#^xc('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']  # 开发环境允许所有主机

# 腾讯云邮件发送服务配置
TENCENT_CLOUD_SECRET_ID = "AKIDobBawBDFGE0ZuVEoJuRlYDg5Lk8PTItG"
TENCENT_CLOUD_SECRET_KEY = "PbaLrBwgNxLWWSExSr561mQs663ujOxO"
TENCENT_CLOUD_REGION = "ap-guangzhou"
EMAIL_FROM = "support@egglittle.cn"
EMAIL_TEMPLATE_ID = 32060  # 腾讯云SES邮件模板ID

# 邮箱验证码相关配置
EMAIL_CODE_EXPIRE_MINUTES = 5  # 验证码有效期(分钟)
EMAIL_CODE_LENGTH = 6  # 验证码长度
EMAIL_SEND_INTERVAL = 60  # 同一邮箱发送间隔(秒)

# === QQ邮箱SMTP配置 ===
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.qq.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = '751041637@qq.com'
EMAIL_HOST_PASSWORD = 'yorukkkfqgembdii'
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # 第三方应用
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'django_filters',
    'django_extensions',
    'social_django',  # 添加social-auth-app-django
    # 'django_crontab',  # 添加crontab支持 - 暂时注释掉
    
    # 自定义应用
    'apps.accounts',
    'apps.vocabulary',
    'apps.learning',
    'drf_yasg',
    'apps.tracking',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware', # session中间件
    'corsheaders.middleware.CorsMiddleware',  # CORS中间件
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS设置
# CORS_ALLOW_ALL_ORIGINS = True  # 开发环境中允许所有源（已用显式列表替代）
CORS_ALLOW_CREDENTIALS = True  # 允许发送 Cookie
# 生产/开发环境显式允许的前端源
CORS_ALLOWED_ORIGINS = [
    "http://111.229.186.241",
    "http://localhost:5173",
    "https://www.egglittle.cn",
    "https://egglittle.cn",
    "https://www.eggbaby.online",
    "https://eggbaby.online",
]
# 更新 CSRF 信任的前端源
CSRF_TRUSTED_ORIGINS = [
    "http://111.229.186.241",
    "http://111.229.186.241:8000",
    "http://localhost:5173",
    "https://www.egglittle.cn",
    "https://egglittle.cn",
    "https://www.eggbaby.online",
    "https://eggbaby.online",
]

# 添加或修改这一部分
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    # 新增以下解决问题的头部
    'cache-control',
    'pragma',
    'expires',
]

ROOT_URLCONF = 'englishlearning.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',  # 添加social-auth context processors
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

# Social Auth 配置
AUTHENTICATION_BACKENDS = [
    'social_core.backends.weixin.WeixinOAuth2',  # 微信OAuth2
    'django.contrib.auth.backends.ModelBackend',  # 默认认证后端
]

# 微信配置
SOCIAL_AUTH_WEIXIN_KEY = 'wxcc9f65f65817f82d'  # 微信AppID
SOCIAL_AUTH_WEIXIN_SECRET = '2bdfba31f78308bbaf16616f854ae0df'  # 微信AppSecret

# 微信登录参数配置
SOCIAL_AUTH_WEIXIN_SCOPE = ['snsapi_login']  # 微信登录权限范围

# 登录完成后重定向URL
SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/dashboard'  # 根据你的前端路由修改
SOCIAL_AUTH_NEW_USER_REDIRECT_URL = '/dashboard'  # 新用户登录后重定向URL

# 使用Cookie存储认证令牌
SOCIAL_AUTH_STRATEGY = 'social_django.strategy.DjangoStrategy'
SOCIAL_AUTH_STORAGE = 'social_django.models.DjangoStorage'

# 认证过程中的pipeline，可以自定义用户创建和关联逻辑
SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.social_auth.associate_by_email',  # 尝试通过邮箱关联已有账户
    'social_core.pipeline.user.create_user',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
    'apps.accounts.pipeline.set_auth_cookie',  # 设置auth_token Cookie
)

WSGI_APPLICATION = 'englishlearning.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'englishlearning',
        'USER': 'postgres',
        'PASSWORD': 'postgres',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# REST Framework设置
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'apps.accounts.authentication.CookieTokenAuthentication',
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.openapi.AutoSchema',
}


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 数据上传限制设置
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000  # 增加字段数量限制，默认为1000
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB，增加内存限制

# Cache settings
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake', # Can be any unique name
    }
}

# 日志配置
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '[{levelname}] {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'log', 'django.log'),
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            # 仅写入 django.log 文件，避免同时输出到 Gunicorn 的 stdout
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': False,  # 禁止向上冒泡，防止日志重复到 gunicorn.log
        },
        'django.request': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',  # 改为DEBUG以捕获所有请求
            'propagate': False,
        },
        'django.server': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',  # 服务器请求日志级别
            'propagate': False,
        },
        'apps': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',  # 改为DEBUG以捕获更多应用日志
            'propagate': False,
        },
    },
}

# Crontab任务配置
CRONJOBS = [
    # 每天凌晨3点执行验证码清理任务
    ('0 3 * * *', 'utils.cleanup_tasks.cleanup_verification_codes', '>> ' + os.path.join(BASE_DIR, 'log', 'verification_cleanup.log') + ' 2>&1'),
]
