# Generated by Django 5.1.7 on 2025-04-13 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_remove_student_interests_student_personality_traits'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabularyBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='新词汇书', max_length=100, verbose_name='书名')),
                ('word_count', models.IntegerField(default=0, verbose_name='词汇量')),
                ('is_system_preset', models.BooleanField(default=False, verbose_name='是否为系统预设书籍')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '书籍',
                'verbose_name_plural': '书籍',
                'db_table': 'vocabulary_books',
            },
        ),
        migrations.CreateModel(
            name='WordBasic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True, verbose_name='单词拼写')),
                ('phonetic_symbol', models.CharField(blank=True, max_length=100, null=True, verbose_name='音标')),
                ('uk_pronunciation', models.URLField(blank=True, null=True, verbose_name='英式发音URL')),
                ('us_pronunciation', models.URLField(blank=True, null=True, verbose_name='美式发音URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '单词基本信息',
                'verbose_name_plural': '单词基本信息',
                'db_table': 'word_basics',
                'indexes': [models.Index(fields=['word'], name='idx_word')],
            },
        ),
        migrations.CreateModel(
            name='StudentCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meanings', models.JSONField(blank=True, null=True, verbose_name='学生自定义的词性及中文释义JSON')),
                ('example_sentence', models.TextField(blank=True, null=True, verbose_name='学生自定义的例句')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_customizations', to='accounts.student', verbose_name='学生')),
                ('word_basic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_customizations', to='vocabulary.wordbasic', verbose_name='单词基本信息')),
            ],
            options={
                'verbose_name': '学生单词自定义',
                'verbose_name_plural': '学生单词自定义',
                'db_table': 'student_customizations',
                'unique_together': {('student', 'word_basic')},
            },
        ),
        migrations.CreateModel(
            name='BookWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_order', models.IntegerField(default=0, verbose_name='单词在书中的顺序')),
                ('meanings', models.JSONField(default=list, verbose_name='词性及中文释义JSON')),
                ('example_sentence', models.TextField(blank=True, null=True, verbose_name='例句')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('vocabulary_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='words', to='vocabulary.vocabularybook', verbose_name='关联的词汇书')),
                ('word_basic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_words', to='vocabulary.wordbasic', verbose_name='关联的单词基本信息')),
            ],
            options={
                'verbose_name': '书籍单词',
                'verbose_name_plural': '书籍单词',
                'db_table': 'book_words',
                'indexes': [models.Index(fields=['vocabulary_book', 'word_order'], name='idx_book_order')],
            },
        ),
    ]
