# Generated by Django 5.1.7 on 2025-04-17 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_student_interests_student_personality_traits'),
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcustomization',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='学生笔记'),
        ),
        migrations.AddField(
            model_name='studentcustomization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddIndex(
            model_name='studentcustomization',
            index=models.Index(fields=['student', 'word_basic'], name='idx_student_word_basic'),
        ),
    ]
