# Generated by Django 5.1.7 on 2025-05-08 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_teacher_teaching_hours'),
        ('vocabulary', '0002_studentcustomization_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentKnownWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marked_at', models.DateTimeField(auto_now_add=True, verbose_name='标记时间')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='known_words_set', to='accounts.student', verbose_name='学生')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='known_by_students', to='vocabulary.wordbasic', verbose_name='单词')),
            ],
            options={
                'verbose_name': '学生已认识单词',
                'verbose_name_plural': '学生已认识单词',
                'db_table': 'vocabulary_studentknownword',
                'ordering': ['-marked_at'],
                'indexes': [models.Index(fields=['student', 'word'], name='idx_student_known_word')],
                'unique_together': {('student', 'word')},
            },
        ),
    ]
