# Generated by Django 5.2.1 on 2025-06-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0003_studentknownword'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookword',
            name='custom_meanings',
            field=models.JSONField(blank=True, null=True, verbose_name='自定义释义（覆盖基础释义）'),
        ),
        migrations.AddField(
            model_name='bookword',
            name='custom_phonetic',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='自定义音标'),
        ),
        migrations.AddField(
            model_name='bookword',
            name='custom_word',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='自定义单词拼写'),
        ),
    ]
