# Generated by Django 5.2.1 on 2025-06-07 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0004_bookword_custom_meanings_bookword_custom_phonetic_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentCustomization',
        ),
    ]
