# Generated by Django 5.1.7 on 2025-04-22 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDurationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('learning', '学习'), ('teaching', '授课'), ('other', '其他')], max_length=20, verbose_name='类型')),
                ('duration', models.PositiveIntegerField(verbose_name='时长（秒）')),
                ('client_start_time', models.DateTimeField(blank=True, null=True, verbose_name='前端开始时间')),
                ('client_end_time', models.DateTimeField(blank=True, null=True, verbose_name='前端结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duration_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户时长日志',
                'verbose_name_plural': '用户时长日志',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'type'], name='tracking_us_user_id_b78e3b_idx')],
            },
        ),
    ]
