# Generated by Django 5.1.7 on 2025-04-22 16:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userdurationlog',
            name='tracking_us_user_id_b78e3b_idx',
        ),
        migrations.AddIndex(
            model_name='userdurationlog',
            index=models.Index(fields=['user', 'type', 'created_at'], name='tracking_us_user_id_7986ff_idx'),
        ),
        migrations.AddIndex(
            model_name='userdurationlog',
            index=models.Index(fields=['created_at'], name='tracking_us_created_0267d1_idx'),
        ),
        migrations.AddIndex(
            model_name='userdurationlog',
            index=models.Index(fields=['client_start_time'], name='tracking_us_client__3b0437_idx'),
        ),
    ]
