# Generated by Django 5.1.7 on 2025-04-24 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_teacher_teaching_hours'),
        ('tracking', '0002_remove_userdurationlog_tracking_us_user_id_b78e3b_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userdurationlog',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_logs', to='accounts.student', verbose_name='关联学生'),
        ),
        migrations.AddIndex(
            model_name='userdurationlog',
            index=models.Index(fields=['student', 'type'], name='tracking_us_student_626f59_idx'),
        ),
    ]
