# Generated by Django 5.1.7 on 2025-05-25 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_userdurationlog_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdurationlog',
            name='word_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='本次新学单词数'),
        ),
        migrations.AddField(
            model_name='userdurationlog',
            name='wrong_word_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='本次错误单词数'),
        ),
    ]
